### ISSUE TITLE
 Consider importing 'dhtmlxgantt' instead of '@types/dhtmlxgantt'.

### ISSUE THREAD

**Issue by priyankasingh2226** [DHTMLX/angular-gantt-demo#11]
C:\Users\Tvash Technologies\gantt\angular2-gantt-demo>ng s --port 8080
Your global Angular CLI version (6.1.3) is greater than your local
version (1.0.0-rc.2). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
** NG Live Development Server is running on http://localhost:8080 **
Hash: 1dd2cbb5dec27515c008
Time: 10593ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 195 kB {4} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.js.map (main) 14.2 kB {3} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.js.map (styles) 45.5 kB {4} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.js.map (vendor) 2.78 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]

ERROR in C:/Users/Tvash Technologies/gantt/angular2-gantt-demo/src/app/components/gantt.component.ts (8,16): File 'C:/Users/Tvash Technologies/gantt/angular2-gantt-demo/node_modules/@types/dhtmlxgantt/index.d.ts' is not a module.)
C:/Users/Tvash Technologies/gantt/angular2-gantt-demo/src/app/components/gantt.component.ts (8,16): Cannot import type declaration files. Consider importing 'dhtmlxgantt' instead of '@types/dhtmlxgantt'.)
webpack: Failed to compile.

**Comment by riceball0907** [comment]
Here is a solution
https://tutel.me/c/programming/questions/50647441/dhtmlx+gantt++error+ts6137+cannot+import+type+declaration+files

**Comment by Jean-Baptiste-Lasselle** [comment]
hi, 
Thank you so much for all open source development here, I think my companyy is going to choose that component (I propose among choices like frappe/gantt ).

Just another comment since issue 's still opened : 
I got the exact same error stack, I'm about to try last comment's solution and will bring feed back ,until then, here are my docker container logs : 
```bash
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated cryptiles@2.0.5: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated boom@2.10.1: This version is no longer maintained. Please upgrade to the latest version.

> node-sass@4.10.0 install /angular2-gantt-demo/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.10.0/linux-x64-67_binding.node
Download complete..] - :
Binary saved to /angular2-gantt-demo/node_modules/node-sass/vendor/linux-x64-67/binding.node
Caching binary to /root/.npm/node-sass/4.10.0/linux-x64-67_binding.node

> node-sass@4.10.0 postinstall /angular2-gantt-demo/node_modules/node-sass
> node scripts/build.js

Binary found at /angular2-gantt-demo/node_modules/node-sass/vendor/linux-x64-67/binding.node
Testing binary
Binary is fine
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN The package @angular/compiler-cli is included as both a dev and production dependency.
npm WARN The package typescript is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1133 packages from 1136 contributors and audited 8628 packages in 58.066s
found 23 vulnerabilities (11 low, 5 moderate, 7 high)
  run `npm audit fix` to fix them, or `npm audit` for details
sh: 1: ng: not found
[jibl@pc-100 ~]$ docker exec -it vinse sh -c "cd angular2-gantt-demo && npm install && npm install -g @angular/cli && ng serve "
npm WARN The package @angular/compiler-cli is included as both a dev and production dependency.
npm WARN The package typescript is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 8628 packages in 11.001s
found 23 vulnerabilities (11 low, 5 moderate, 7 high)
  run `npm audit fix` to fix them, or `npm audit` for details
/usr/local/bin/ng -> /usr/local/lib/node_modules/@angular/cli/bin/ng
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/@angular/cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ @angular/cli@7.0.4
added 265 packages from 205 contributors in 9.157s
Your global Angular CLI version (7.0.4) is greater than your local
version (1.0.0-rc.2). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
** NG Live Development Server is running on http://localhost:4200 **
Hash: ce5f5743b2203c013bfa                                                              
Time: 9129ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 195 kB {4} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.js.map (main) 13.9 kB {3} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.js.map (styles) 45.5 kB {4} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.js.map (vendor) 2.78 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]

ERROR in /angular2-gantt-demo/src/app/components/gantt.component.ts (8,16): File '/angular2-gantt-demo/node_modules/@types/dhtmlxgantt/index.d.ts' is not a module.)
/angular2-gantt-demo/src/app/components/gantt.component.ts (8,16): Cannot import type declaration files. Consider importing 'dhtmlxgantt' instead of '@types/dhtmlxgantt'.)
webpack: Failed to compile.

```

[Quoted solution](https://tutel.me/c/programming/questions/50647441/dhtmlx+gantt++error+ts6137+cannot+import+type+declaration+files) : 

> 
> Looks like the type definitions of dhtmlx-gantt appears to be not compatible with typescript 2.9.1 (released yesterday https://github.com/Microsoft/TypeScript/releases/tag/v2.9.1 )
> 
> The type definitions of dhtmlxGantt haven't been updated in a while, which is a main reason of the problem.
> 
> As a possible workaround for now, you can either downgrade the typescript in your project to 2.8.x (I've checked the build seems to be working on 2.8.4)
> 
>     `npm uninstall typescript`
> 
>     `npm install typescript@2.8.4`
> 
> or, specify the typescript version in package.json "typescript": "2.8.4",
> 
> If downgrading is not an option, you can remove type definitions of dhtmlx gantt and declare gantt instance manually: declare let gantt: any;
> 
> obviously, you'll lose the type info, but it still seems to be better than the project that won't compile


**My test 1**

I use updating `./package.json` dependency, first, because it allows quickest versionning of operations.
I have in my new package.json, `"typescript": "2.8.4"`, instead of  `"typescript": "^2.2.2"` : 

```bash
npm uninstall -g @angular/cli
npm install -g @angular/cli@6.1.3 
# assuming package.json has been updated with specific  "typescript": "2.8.4", in the master's branch latest commit on repo 'https://github.com/DHTMLX/angular2-gantt-demo' :+1: 
apt-get update -y 
apt-get install -y git vim
git clone "https://github.com/DHTMLX/angular2-gantt-demo" .
cd angular2-gantt-demo 
npm install -g @angular/cli@6.1.3 
npm uninstall typepescript 
npm update 
npm install 

# now I run the whole thing again
# I run all this inside a container, I wanna be able to reach the app from
# outside that container, so I bind angular-cli dev server 's socket to
# the (debian/centos/ubuntu) linux default net interface, aka '0.0.0.0' (just as
# standardized as 'localhost')  
ng serve --host 0.0.0.0
```
I want to point out I carried out a sanity measure there : I forced an accurate version of Angular CLI, here, to match the version @priyankasingh2226   used in his tests (thank you  @priyankasingh2226 , for posting your logs, in which I could recover Angular CLI 's version you ran) 

And there I go.

Great, now it works !

Thank you all team, I'll now try and setup other more advanced examples of that component, with minimum demo server-side, all dockerized. I'll update team then !

**Comment by AlexKlimenkov** [comment]
Hi,
I've updated the demo for Angular 7 https://github.com/DHTMLX/angular2-gantt-demo/commit/512fed7e51422124bdfed76fed6202e136b3039e 
Types are imported at `tsconfig.app.json` and all should work as expected with the latest typescript:
https://github.com/DHTMLX/angular2-gantt-demo/commit/512fed7e51422124bdfed76fed6202e136b3039e#diff-f90bfb8a30305d68976bd6bd86ab64b3R6

Pls feel free to reopen or create the new issue if you see anything weird with the update.

Also, thanks to @duayres , type definitions were updated and now work correctly with the latest typescript
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30311
