### ISSUE TITLE
Angular 6 Documentation

### ISSUE THREAD

**Issue by vigneshbarani24** [DHTMLX/angular-gantt-demo#12]
Hey Team,

Great Component, Would love to see the Documentation for Angular 6

**Comment by AlexKlimenkov** [comment]
Hi,
I've updated the demo for Angular 7 https://github.com/DHTMLX/angular2-gantt-demo/commit/512fed7e51422124bdfed76fed6202e136b3039e 

Can't give you an ETA for the updated tutorial, though.
