### ISSUE TITLE
remove line

### ISSUE THREAD

**Issue by guypeled1** [DHTMLX/angular-gantt-demo#15]
How can i remove this line:https://prnt.sc/q7u0rd
and how can i control the tasks colors (each task in different color)?

Thanks

**Comment by AlexKlimenkov** [comment]
Hi,

> How can i remove this line:https://prnt.sc/q7u0rd

This is a link (relation) that comes from the data you load into the gantt. In this repo the data is hardcoded:
https://github.com/DHTMLX/angular2-gantt-demo/blob/master/src/app/services/in-memory-data.service.ts#L10
https://docs.dhtmlx.com/gantt/desktop__loading.html

If you don't need to display/create links completely, you can also disable them using these configs
https://docs.dhtmlx.com/gantt/api__gantt_drag_links_config.html
https://docs.dhtmlx.com/gantt/api__gantt_show_links_config.html

> and how can i control the tasks colors (each task in different color)?

Please check this article
https://docs.dhtmlx.com/gantt/desktop__colouring_tasks.html
