### ISSUE TITLE
change left column

### ISSUE THREAD

**Issue by guypeled1** [DHTMLX/angular-gantt-demo#16]
Hi,
How can i change this columns: https://prnt.sc/q97kub
and there is an option to change the html of them like adding elements?

Thanks

**Comment by gearcoded** [comment]
Hello,
The following articles explain how to change the column configuration:
https://docs.dhtmlx.com/gantt/desktop__specifying_columns.html
https://docs.dhtmlx.com/gantt/api__gantt_columns_config.html

If you want to change the appearance of the plus button, you can do that via CSS:
https://snippet.dhtmlx.com/1baaf3918

Another way is to specify any name except `add` in the column configuration and return the HTML element you need with the necessary functions:
https://snippet.dhtmlx.com/1b247fefc
http://snippet.dhtmlx.com/0f60061be
http://snippet.dhtmlx.com/186c8dc4b
