### ISSUE TITLE
last cell ui

### ISSUE THREAD

**Issue by guypeled1** [DHTMLX/angular-gantt-demo#17]
Hi,
How can i change the last cell html: https://prnt.sc/qchyyk
i want to remove this file icon and to add a left border by the object attribute.

Thanks

**Comment by gearcoded** [comment]
Hello,
You can change it by modifying the `grid_file` template:
https://docs.dhtmlx.com/gantt/api__gantt_grid_file_template.html
There, you can return any HTML element with any properties. Here are examples of how it works:
http://snippet.dhtmlx.com/4253d47f8
http://snippet.dhtmlx.com/a2c2bad93
