### ISSUE TITLE
getWBSCode not declared on GanttStatict methods declaration.

### ISSUE THREAD

**Issue by duayres** [DHTMLX/angular-gantt-demo#7]
The following (available on vanilla) method: `getWBSCode(id: string|number): string;` is not present on GanttStatic methods declaration in index.d.ts on the node_modules/@types definition (vendor) package.

I have no ideia on how to contribute, nor to compile my node_modules to use this.

**Comment by AlexKlimenkov** [comment]
Hi,
the type definitions of dhtmlxgantt at definitelyTyped are a bit outdated now and don't have the latest api.
We'll send them a PR with an update in a day or two. As a temporary solution you can remove @types/dhtmlxgantt import from your code and declare gantt instance manually:
`declare let gantt: any;`
it'll disable code auto-completion, as well as compile-time arguments checks, but you'll be able to use all methods available in js gantt object.

**Comment by AlexKlimenkov** [comment]
We're now finally able to generate type definitions somewhat automatically and I've updated them to the latest gantt 6.0 api https://www.npmjs.com/package/@types/dhtmlxgantt
So everything should be good now and we'll try to keep type definitions up to date from now on.
