### ISSUE TITLE
Types not maintained

### ISSUE THREAD

**Issue by ghost** [DHTMLX/angular-gantt-demo#8]
There are many missing Types and settings from the pro version not maintained in the @types/dhtmlxgantt NPM package

https://www.npmjs.com/package/@types/dhtmlxgantt

Eg.

- GanttConfigOptions.drag_project: boolean;
- GanttStatic.exportToPDF(config: any): void;
- GanttStatic.exportToPNG(config: any): void;
- GanttStatic.exportToExcel(config: any): void;
- GanttStatic.exportToMSProject(config: any): void;

**Comment by AlexKlimenkov** [comment]
Should be updated now https://www.npmjs.com/package/@types/dhtmlxgantt
