### ISSUE TITLE
Form are not showing inside my application

### ISSUE THREAD

**Issue by NeVeR2TrY** [DHTMLX/angular-gantt-demo#9]
![gantt](https://user-images.githubusercontent.com/20230555/39957399-359b8ce4-55fb-11e8-830f-36bcd396db4f.PNG)

**Comment by AlexKlimenkov** [comment]
If it's still actual - please try the latest version from the repo.
Overal it looks like dhtmlxgantt.css hasn't been loaded or hasn't been applied on the page.
Please be sure you import it somewhere, e.g.
https://github.com/DHTMLX/angular2-gantt-demo/blob/master/src/app/components/gantt.component.css#L1

You may also need to disable view incapsulation for gantt component:
https://github.com/DHTMLX/angular2-gantt-demo/blob/master/src/app/components/gantt.component.ts#L10
